package com.subtitle.reader.util

object Strings {
    private val ZH = mapOf(
        "app_name" to "字幕阅读器",
        "open" to "打开",
        "open_folder" to "打开文件夹",
        "open_folder_hint" to "点击打开文件夹\n选择字幕文件 (.srt / .sub / .ass)",
        "filter_all" to "全部",
        "filter_srt" to "SRT",
        "filter_sub" to "SUB",
        "filter_ass" to "ASS",
        "export" to "导出",
        "timecode" to "时间码",
        "line_no" to "行号",
        "duration" to "时长",
        "font" to "字体",
        "text_color" to "文字颜色",
        "bg_color" to "背景颜色",
        "no_file" to "未加载字幕。\n打开 .srt/.sub/.ass 文件开始阅读。",
        "export_title" to "导出字幕",
        "export_txt" to "文本 (.txt)",
        "export_docx" to "Word (.docx)",
        "choose_format" to "选择格式：",
        "cancel" to "取消",
        "select_font" to "选择字体",
        "close" to "关闭",
        "text_color_title" to "文字颜色",
        "bg_color_title" to "背景颜色",
        "presets" to "预设颜色：",
        "current" to "当前：",
        "file" to "文件：",
        "export_hint" to "打开一个字幕文件后可使用此功能",
        "language" to "语言",
        "lang_zh" to "中文",
        "lang_en" to "English",
        "hint" to "打开字幕文件 (.srt / .sub / .ass)",
        "close_file" to "关闭文件",
        "recent_files" to "最近打开",
        "no_recent_files" to "没有最近打开的文件",
        "confirm_close" to "确定关闭当前文件？",
        "yes" to "确定",
        "no" to "取消",
        "clear_recent" to "清除记录",
        "clear_recent_confirm" to "确定清除所有最近打开记录？",
        "favorites" to "收藏的文件夹",
        "favorite_toggle" to "收藏/取消收藏",
        "no_files" to "此文件夹中没有可读取的字幕文件",
        "back" to "返回",
        "browse_other" to "选择其他文件夹",
        "load_fail" to "无法读取该文件",
        "jump_to" to "跳转到位置",
        "jump_to_hint" to "请输入百分比 (0-100)：",
        "mode_percent" to "百分比%",
        "mode_page" to "分页",
        "page_fmt" to "第{}页/共{}页",
        "page_jump_hint" to "请输入页数 (1-{})：",
        "menu_about" to "关于",
        "about_info" to "subtitle-reader v2.0\n字幕阅读器 v2.0\n作者:武东东\n开源地址",
        "custom_color" to "自定义颜色：",
        "confirm" to "确认",
        "red" to "红",
        "green" to "绿",
        "blue" to "蓝",
        "brightness" to "亮度",
    )

    private val EN = mapOf(
        "app_name" to "Subtitle Reader",
        "open" to "Open",
        "open_folder" to "Open Folder",
        "open_folder_hint" to "Tap to open a folder\nand pick a subtitle (.srt / .sub / .ass)",
        "filter_all" to "All",
        "filter_srt" to "SRT",
        "filter_sub" to "SUB",
        "filter_ass" to "ASS",
        "export" to "Export",
        "export" to "Export",
        "timecode" to "Timecode",
        "line_no" to "Line No.",
        "duration" to "Duration",
        "font" to "Font",
        "text_color" to "Text Color",
        "bg_color" to "Bg Color",
        "no_file" to "No subtitles loaded.\nOpen a .srt / .sub / .ass file to begin.",
        "export_title" to "Export Subtitle",
        "export_txt" to "Text (.txt)",
        "export_docx" to "Word (.docx)",
        "choose_format" to "Choose format:",
        "cancel" to "Cancel",
        "select_font" to "Select Font",
        "close" to "Close",
        "text_color_title" to "Text Color",
        "bg_color_title" to "Background Color",
        "presets" to "Presets:",
        "current" to "Current:",
        "file" to "File:",
        "export_hint" to "Open a subtitle file first",
        "language" to "Language",
        "lang_zh" to "中文",
        "lang_en" to "English",
        "hint" to "Open a subtitle file (.srt / .sub / .ass)",
        "close_file" to "Close File",
        "recent_files" to "Recent Files",
        "no_recent_files" to "No recent files",
        "confirm_close" to "Close current file?",
        "yes" to "Yes",
        "no" to "No",
        "clear_recent" to "Clear Recent Files",
        "clear_recent_confirm" to "Clear all recent files?",
        "favorites" to "Favorite Folders",
        "favorite_toggle" to "Toggle favorite",
        "no_files" to "No readable subtitle files in this folder",
        "back" to "Back",
        "browse_other" to "Choose another folder",
        "load_fail" to "Cannot read this file",
        "jump_to" to "Jump to Position",
        "jump_to_hint" to "Enter percentage (0-100):",
        "mode_percent" to "Percentage %",
        "mode_page" to "Paging",
        "page_fmt" to "Page {}/{}",
        "page_jump_hint" to "Enter page (1-{}):",
        "menu_about" to "About",
        "about_info" to "subtitle-reader v2.0\n字幕阅读器 v2.0\nAuthor:武东东\nSource",
        "custom_color" to "Custom:",
        "confirm" to "Apply",
        "red" to "R",
        "green" to "G",
        "blue" to "B",
        "brightness" to "Brightness",
    )

    private var currentLang = "zh"

    fun setLanguage(lang: String) {
        currentLang = lang
    }

    fun getLanguage(): String = currentLang

    fun get(key: String): String {
        val map = if (currentLang == "zh") ZH else EN
        return map[key] ?: key
    }
}
